FROM alpine:latest
MAINTAINER furious.luke@gmail.com

RUN mkdir -p /run/nginx/templ && \
    apk add --update nginx gettext && \
    rm -rf /var/cache/apk/*

ENV dummy=1
ADD boilerplate/docker/nginx.dev.conf /etc/nginx/templ/nginx.conf
ADD boilerplate/docker/nginx /etc/nginx/nginx
ADD boilerplate/keys /etc/nginx/keys

ENV PORT=80
ENV SERVER_NAME=dev

CMD envsubst '$SERVER_NAME $UPSTREAM' < /etc/nginx/templ/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'
