version: '2'
services:

  db:
    image: aidanlister/postgres-hstore:latest

  redis:
    image: redis:alpine

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      - BACKUP_ENCRYPT_PW=testing
      - HEROKU_TOOLBELT_API_EMAIL
      - HEROKU_TOOLBELT_API_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    links:
      - db
      - redis
    volumes:
      - ./var:/usr/local/app/var

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    environment:
      - PORT=8080
      - WEB_CONCURRENCY=1
      - KEYFILE=keys/dev.key
      - CERTFILE=keys/dev.cert
      - BACKUP_ENCRYPT_PW=testing
      - HEROKU_TOOLBELT_API_EMAIL
      - HEROKU_TOOLBELT_API_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - 8080:8080
    links:
      - db
      - redis
    volumes:
      - ./var:/usr/local/app/var
      - ./keys:/usr/local/app/keys
