version: '2'
services:

  db:
    image: aidanlister/postgres-hstore:latest

  redis:
    image: redis:alpine

  worker:
    build:
      context: ../..
      dockerfile: ./boilerplate/docker/Dockerfile.worker
    links:
      - db
      - redis
    volumes:
      - ../../var:/app/user/var

  web:
    build:
      context: ../..
      dockerfile: ./boilerplate/docker/Dockerfile.web
    environment:
      - PORT=8080
      - WEB_CONCURRENCY=1
      - KEYFILE=keys/dev.key
      - CERTFILE=keys/dev.cert
    ports:
      - 8080:8080
    links:
      - db
      - redis
    volumes:
      - ../../var:/app/user/var
      - ../keys:/app/user/keys
